version: '3.1'

services:

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/niverdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=admin1234
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/niverdb
      - SERVER_SSL_KEY_STORE_PASSWORD=test123
      - SERVER_SSL_KEY_ALIAS=keystore
    ports:
      - "8090:8090"

  db:
    container_name: pg_container
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: niverdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db-data: