spring:
  jpa:
    generate-ddl: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    properties:
      hibernate:
        format_sql=true: 'true'

  mail:
    host: smtp.gmail.com
    username: ALTERAR
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ALTERAR

  datasource:
    password: admin123
    username: postgres
    url: jdbc:postgresql://localhost:5432/niverdb

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/niverdb
    schemas: public
    user: postgres
    password: admin123
    locations: "classpath:db/migration"
    baselineOnMigrate: 'true'

server:
  port: '8090'

jwt:
  secret: secret